version: "3.9"
services:
  kafka-rest-app:
    ports:
      - "8080:8080"
    image: "kafka-rest-app"
    depends_on:
      - "kafka-cluster"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka-cluster:9092
  zookeeper:
    image: "docker.io/bitnami/zookeeper"
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-cluster:
    image: "docker.io/bitnami/kafka"
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
