version: "3.9"
services:
  kafka-rest-app:
    ports:
      - "8080:8080"
    image: "kafka-rest-app"
    depends_on:
      - "kafka-cluster"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka-cluster:9092
      JAVA_TOOL_OPTIONS: -Xmx512m -Xms128m
      KAFKA_REST_APP_AUTO_CREATE_TOPICS: '
        [
          {"name": "test-topic-1", "partitions":3},
          {"name": "test-topic-2", "partitions":1}
        ]
      '
  kafka-ui:
    image: "provectuslabs/kafka-ui"
    ports:
      - "8088:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-cluster:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2128

  kafka-cluster:
    image: "docker.io/bitnami/kafka"
    ports:
      - "9092:9093"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-cluster:9092,EXTERNAL://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  zookeeper:
    image: "docker.io/bitnami/zookeeper"
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
